#!/usr/bin/env python
import threading
import time
import random
import datetime

fruit = 'pineapple grape coconut tangerine grapefruit apple pear cranberry lemon lime peach apricot'.split()
vegetable = 'brocolli green_bean carrot celery arugula romaine brussels_sprout cauliflower peas'.split()
sql = [
  "SELECT * FROM user",
  "UPDATE user SET name = 'Heidi' WHERE id = 12",
  "DELETE FROM furniture WHERE NOT comfortable",
  "INSERT INTO skills VALUES ('juggling'), ('snowshoeing')"
]
access = [
  "/index.html",
  "/favicon.ico",
  "/robots.txt",
  "/wp-admin/",
  "/home",
  "/humans.txt"]

def write_logs(name, lst, sleep_secs):
  while True:
    w = random.choice(lst)
    with open('logs/' + name + '.log', 'a') as f:
      f.write('{} {}\n'.format(datetime.datetime.now().isoformat(), w))
    time.sleep(sleep_secs + abs(random.normalvariate(0, 1)))

args = [
  ('fruit', fruit, 2),
  ('vegetable', vegetable, 2),
  ('sql', sql, 3),
  ('access', access, 0.1),
]

threads = []

for arg in args:
  t = threading.Thread(target=write_logs, args=arg)
  t.daemon = True
  threads.append(t)
  t.start()

print("writing logs...")
try:
  while True:
    time.sleep(0.25)
except KeyboardInterrupt:
  pass